- alias: Turn on lights when bot1 is switched on
  id: turn_on_lights_bot1_on
  description: Activates lights when the bot1 switch is turned on.
  trigger:
    platform: state
    entity_id: switch.bot1
    to: 'on'
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.tall_lamp
          - light.short_lamp
  mode: single